### ISSUE TITLE
React SDK implementation

### ISSUE THREAD

**Issue by toddbaert** [open-feature/js-sdk#545]
We should implement a React SDK. The SDK would provide a "React-friendly" API and features, built on top of the [Web SDK](https://github.com/open-feature/js-sdk/tree/main/packages/client).

:warning: Below is a _**tentative**_ list of features we should implement (some points include questions, _and all of these are up for debate_) :warning: 

- [x] a [context provider](https://react.dev/learn/passing-data-deeply-with-context) for initializing the SDK and allowing access to flag values across components
  - we may want to allow this context provider to be bound to a particular `client-name` to support multiple providers, provider-client mapping 
- [x] a `useStatus` [hook](https://react.dev/reference/react#your-own-hooks) which corresponds to associated provider status and last fired provider readiness event
  - useful for showing spinners/loaders while provider's init, if authors would like to wait before rendering content sensitive to flags
- [x] `useFlagValue/useFlagDetails` hooks, which can be used to impact rendering based on flag values
  - should this API be generic? Or should we do `useBooleanFlagValue`, etc?
  - should facilitate real-time, dynamic updates when providers emit `PROVIDER_CONFIGURATION_CHANGED` events

Non-functional requirements:

- consistent terminology and naming with Web SDK and OpenFeature spec
- observe React idioms and patterns
- helpful documentation (`useEffect` to update context, explanations for all the features/APIs above, configuration)
  - included in https://openfeature.dev/ecosystem/ page
- minimal implementation (only "react-ish") things should be implemented here, general enhancements should be made in the Web SDK if needed
- accurate peer dependency for the Web SDK
- helpful types

Precedents:

- featurevisor react SDK: https://featurevisor.com/docs/react/
- LaunchDarkly react SDK: https://docs.launchdarkly.com/sdk/client-side/react/react-web
- Spotify Confidence SDK: https://github.com/spotify/confidence-openfeature-provider-js/tree/main/packages/integration-react

**Comment by toddbaert** [comment]
I've opened https://github.com/open-feature/js-sdk/pull/546, which mostly just lays the repo groundwork, but also has a basic implementation (NOT FINAL) by @moredip.

I've also transferred this issue to the js-sdk (out of contrib).

**Comment by juanparadox** [comment]
Have we given any thought to adding some kind of `<OpenFeature>{some child}</OpenFeature>` component that takes in a feature flag boolean result and based on that result conditionally renders the `children`?

A possible benefit of a component that renders some thing based on a feature flag is that it can Suspend the render of the children until two conditions are met - the provider event is set to ready and the feature is `true`.

I also understand if this is overkill:
- If we should expect the 'readiness' of the consuming components to have only rendered if the status of the set provider is ready then this is a redundancy
- If using the `useFeatureFlag` hook is enough then this is definitely a redundancy

**Comment by toddbaert** [comment]
> Have we given any thought to adding some kind of `<OpenFeature>{some child}</OpenFeature>` component that takes in a feature flag boolean result and based on that result conditionally renders the `children`?
> 
> A possible benefit of a component that renders some thing based on a feature flag is that it can Suspend the render of the children until two conditions are met - the provider event is set to ready and the feature is `true`.
> 
> I also understand if this is overkill:
> 
> * If we should expect the 'readiness' of the consuming components to have only rendered if the status of the set provider is ready then this is a redundancy
> * If using the `useFeatureFlag` hook is enough then this is definitely a redundancy

@juanparadox 

That's an interesting idea... it sounds like a combination of `useStatus` hook I mentioned above with a `useFlag` boolean hook. So it seems like "syntactic sugar", but possibly worth adding. I think it'd have to support an arg for a provider name as well, but I think it makes sense. We'd need to work on a better name though as well I think. Maybe `ShowFeature` or `IsEnabled`?

**Comment by moredip** [comment]
Yeah it's an interesting idea - a lot of React codebases end up with an internal version of this. 

We'd probably also want to support an A/B type thing, where you specify what the `on` and `off` components should be. The Split documentation has an example of a basic "toggler" component that does this: https://help.split.io/hc/en-us/articles/360038825091-React-SDK#get-treatments-with-configurations

**Comment by toddbaert** [comment]
Closing with [first non-experimental release](https://github.com/open-feature/js-sdk/commit/5e28dbb81a624e5548ada57e729b1c8c5cdf6797).
